CREATE TABLE `all_types` (
     `id` int(11) NOT NULL AUTO_INCREMENT,
     `tiny_signed` tinyint(4) DEFAULT NULL,
     `tiny_unsigned` tinyint(3) unsigned DEFAULT NULL,
     `small_signed` smallint(6) DEFAULT NULL,
     `small_unsigned` smallint(5) unsigned DEFAULT NULL,
     `medium_signed` mediumint(9) DEFAULT NULL,
     `medium_unsigned` mediumint(8) unsigned DEFAULT NULL,
     `int_signed` int(11) DEFAULT NULL,
     `int_unsigned` int(10) unsigned DEFAULT NULL,
     `big_signed` bigint(20) DEFAULT NULL,
     `big_unsigned` bigint(20) unsigned DEFAULT NULL,
     `float_field` float DEFAULT NULL,
     `double_field` double DEFAULT NULL,
     `real_field` double DEFAULT NULL,
     `decimal_field` decimal(30,10) DEFAULT NULL,
     `dec_field` decimal(20,5) DEFAULT NULL,
     `numeric_field` decimal(15,7) DEFAULT NULL,
     `fixed_field` decimal(18,6) DEFAULT NULL,
     `bit1` bit(1) DEFAULT NULL,
     `bit8` bit(8) DEFAULT NULL,
     `bit64` bit(64) DEFAULT NULL,
     `bool_field` tinyint(1) DEFAULT NULL,
     `boolean_field` tinyint(1) DEFAULT NULL,
     `char_field` char(10) DEFAULT NULL,
     `varchar_field` varchar(255) DEFAULT NULL,
     `text_field` text DEFAULT NULL,
     `tinytext_field` tinytext DEFAULT NULL,
     `mediumtext_field` mediumtext DEFAULT NULL,
     `longtext_field` longtext DEFAULT NULL,
     `enum_field` enum('one','two','three') DEFAULT NULL,
     `set_field` set('a','b','c') DEFAULT NULL,
     `binary_field` binary(16) DEFAULT NULL,
     `varbinary_field` varbinary(255) DEFAULT NULL,
     `blob_field` blob DEFAULT NULL,
     `tinyblob_field` tinyblob DEFAULT NULL,
     `mediumblob_field` mediumblob DEFAULT NULL,
     `longblob_field` longblob DEFAULT NULL,
     `date_field` date DEFAULT NULL,
     `time_field` time DEFAULT NULL,
     `year_field` year(4) DEFAULT NULL,
     `datetime_field` datetime(6) DEFAULT NULL,
     `timestamp_field` timestamp NULL DEFAULT NULL,
     `uuid_field` char(36) DEFAULT NULL,
     PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
